- hosts: localhost
  become: yes
  tasks:
  - name: Install apache
    ansible.builtin.apt:
      name:
        - apache2
        - tree
      state: present
      update_cache: yes

  - name: Install tree
    ansible.builtin.apt:
      name: tree
      state: present

  - name: Start apache
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes
